version: 2.2.2.{build}
configuration: Release
before_build:
- cd src
- nuget restore
image: Visual Studio 2019
build:
  verbosity: minimal
  project: ./src/LogoFX.Client.Mvvm.View.Extensions.sln
after_test:
- cd ../devops
- cd pack
- call ./pack.bat
artifacts:
- name: Packages
  path: ./output/*.nupkg
...
